Repository Gooroom-Study-Gigigit/INTIP-refactoring, pull requests merged in 2024-12, with the labels that each got.

#12 refactor: 댓글 서비스 분리, 베스트 댓글 로직 수정
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/kr/inuappcenterportal/inuportal/InuPortalApplication.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/controller/MemberController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/controller/PostController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/service/PostService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/controller/ReplyController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/repository/ReplyRepository.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyCommandService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyLikeService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyQueryService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyService.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/MySqlConfig.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/SecurityConfig.java
  src/main/java/kr/inuappcenterportal/inuportal/global/service/RedisService.java
  src/test/java/kr/inuappcenterportal/inuportal/controller/MemberControllerTest.java
Labels: refactor

#10 test : Report 테스트 구현 및 수정
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/inu-portal.main.iml
  .idea/vcs.xml
  build.gradle
  src/main/java/kr/inuappcenterportal/inuportal/domain/report/model/Report.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/report/service/ReportService.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/MySqlConfig.java
  src/test/java/kr/inuappcenterportal/inuportal/repository/ReportRepositoryTest.java
  src/test/java/kr/inuappcenterportal/inuportal/service/ReportServiceSpringTest.java
Labels: bug, test

#23 refactor: PostService 리팩토링
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/controller/PostController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/service/PostCommonService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/service/PostImageService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/service/PostService.java
Labels: refactor

#24 refactor: 토큰 관리 방식 변경 및 로그인 리펙토링
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/controller/MemberController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/dto/TokenDto.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/service/MemberService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/util/CookieUtil.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/TokenProvider.java
  src/main/java/kr/inuappcenterportal/inuportal/global/service/RedisService.java
  src/test/java/kr/inuappcenterportal/inuportal/controller/MemberControllerTest.java
  src/test/java/kr/inuappcenterportal/inuportal/domain/member/util/CookieUtilTest.java
  src/test/java/kr/inuappcenterportal/inuportal/global/service/RedisServiceTest.java
Labels: feat, refactor

#8 refactor: CafeteriaService 가독성 향상
  src/main/java/kr/inuappcenterportal/inuportal/domain/cafeteria/model/Day.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/cafeteria/model/MealType.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/cafeteria/service/CafeteriaService.java
Labels: refactor

#22 refactor: 학사일정 크롤링 롤백 안정화로 개선
  src/main/java/kr/inuappcenterportal/inuportal/domain/schedule/model/Schedule.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/schedule/repository/ScheduleRepository.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/schedule/service/ScheduleService.java
Labels: refactor

#29 test : folder 도메인 서비스 단위 테스트 코드 일부 추가
  .idea/.name
  src/main/java/kr/inuappcenterportal/inuportal/global/exception/ex/MyException.java
  src/test/java/kr/inuappcenterportal/inuportal/domain/folder/service/FolderServiceTest.java
Labels: test

#27 refactor: 재발급 기능 수정 및 상수 이동
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/controller/MemberController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/service/MemberService.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/TokenProvider.java
Labels: refactor

#26 fix, refactor: n+1 문제 해결, countAnonymousNumber 문제 해결, sql 파일 추가, replyLikeService 코드 수정
  .gitignore
  src/main/java/kr/inuappcenterportal/inuportal/InuPortalApplication.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/controller/MemberController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/post/service/PostService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/controller/ReplyController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/dto/ReReplyResponseDto.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/dto/ReplyDto.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/dto/ReplyListResponseDto.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/dto/ReplyResponseDto.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/model/Reply.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/repository/ReplyRepository.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyCommandService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyLikeService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyQueryService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/reply/service/ReplyService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/replylike/model/LikeAction.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/replylike/repository/LikeReplyRepository.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/TokenProvider.java
  src/main/java/kr/inuappcenterportal/inuportal/global/service/RedisService.java
  src/sql/data.sql
  src/test/java/kr/inuappcenterportal/inuportal/controller/MemberControllerTest.java
  src/test/java/kr/inuappcenterportal/inuportal/controller/ReplyControllerTest.java
  src/test/java/kr/inuappcenterportal/inuportal/custom/MockCustomUserSecurityContextFactory.java
  src/test/java/kr/inuappcenterportal/inuportal/custom/WithMockCustom.java
Labels: bug, refactor

#33 feat: 로그아웃 기능 추가
  src/main/java/kr/inuappcenterportal/inuportal/InuPortalApplication.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/controller/MemberController.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/service/MemberService.java
  src/main/java/kr/inuappcenterportal/inuportal/domain/member/util/CookieUtil.java
  src/main/java/kr/inuappcenterportal/inuportal/global/config/TokenProvider.java
Labels: feat
